site_name: PhenEx - Automatic Electronic Phenotype Execution
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Data Model: data_model.md
  - Roadmap: roadmap.md
  - Tutorials:
      - Phenex Study Tutorial: tutorials/PhenEx_Study_Tutorial.ipynb
      - CodelistPhenotype: tutorials/CodelistPhenotype_Tutorial.ipynb
      - MeasurementPhenotype: tutorials/MeasurementPhenotype_Tutorial.ipynb
      - ArithmeticPhenotype: tutorials/ArithmeticPhenotype_Tutorial.ipynb
      - LogicPhenotype: tutorials/LogicPhenotype_Tutorial.ipynb
      - Python For PhenEx Tutorial: tutorials/Python_For_Phenex_Tutorial.ipynb
  - API:
      - Phenotypes:
          - Phenotype: api/phenotypes/phenotype.md
          - CodelistPhenotype: api/phenotypes/codelist_phenotype.md
          - MeasurementPhenotype: api/phenotypes/measurement_phenotype.md
          - AgePhenotype: api/phenotypes/age_phenotype.md
          - SexPhenotype: api/phenotypes/sex_phenotype.md
          - DeathPhenotype: api/phenotypes/death_phenotype.md
          - TimeRangePhenotype: api/phenotypes/time_range_phenotype.md
          - EventCountPhenotype: api/phenotypes/event_count_phenotype.md
          - WithinSameEncounterPhenotype: api/phenotypes/within_same_encounter_phenotype.md
          - UserDefinedPhenotype: api/phenotypes/user_defined_phenotype.md
          - BinPhenotype: api/phenotypes/bin_phenotype.md
          - ArithmeticPhenotype: api/phenotypes/arithmetic_phenotype.md
          - LogicPhenotype: api/phenotypes/logic_phenotype.md
          - ScorePhenotype: api/phenotypes/score_phenotype.md
          - Cohort: api/phenotypes/cohort.md
          - Factory:
            - ISTHMajorBleed: api/phenotypes/factory/isth_major_bleed.md
      - Filters:
          - Filter: api/filters/filter.md
          - ValueFilter: api/filters/value_filter.md
          - DateFilter: api/filters/date_filter.md
          - RelativeTimeRangeFilter: api/filters/relative_time_range_filter.md
          - CodelistFilter: api/filters/codelist_filter.md
          - CategoricalFilter: api/filters/categorical_filter.md
      - Codelists:
          - Codelist: api/codelists/codelists.md
          - LocalCSVCodelistFactory: api/codelists/local_csv_codelist_factory.md
      - Connectors:
          - Connectors: api/ibis_connect.md
          - Mappers: api/mappers.md
          - DomainsDictionary: api/domains_dictionary.md
      - Reporting:
          - Report: api/reporting/reporter.md
          - Table1: api/reporting/table1.md
          - Waterfall: api/reporting/waterfall.md
          - InExCounts: api/reporting/counts.md
          - TimeToEvent: api/reporting/time_to_event.md
      - Util:
          - Serialization: api/util/serialization.md
  - License: LICENSE.md

site_url: https://bayer-group.github.io/PhenEx/
repo_url: https://github.com/bayer-group/PhenEx
edit_uri: edit/main/docs/

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [../phenex] # search packages in the src folder
          options:
            docstring_style: "google" # or "numpy", "restructuredtext", etc.
            inherited_members: true
  - mkdocs-jupyter
theme:
  name: material
  palette:
    primary: deep orange
    accent: deep orange
  features:
    - content.code.copy
    - content.action.edit
  favicon: assets/bird_icon.png
  logo: assets/bird_icon_white.png
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: false # Try setting this to false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde

extra_css:
  - assets/style.css
